/*
 * NDC AirShopping diff engine — port of src/airshop/ndc/diff.py.
 *
 * Runs entirely in the browser: no server, no Python, no network. The algorithms
 * are ported one-for-one from the Python implementation so both produce the same
 * report for the same inputs; web/verify.mjs asserts that equivalence against a
 * reference report generated by the Python code.
 *
 * Packaged as a UMD-style global/CommonJS module rather than an ES module, so
 * index.html also works when opened directly from disk (file://), where browsers
 * block ES module loading.
 */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (typeof globalThis !== "undefined") globalThis.NDC = api;
  if (root && typeof root === "object") root.NDC = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

// ID-bearing NDC collections: element name -> where its identifying value lives.
//
// A value starting with "@" names an attribute; anything else names a child
// element. Both forms occur in real payloads — carriers emit
// BaggageAllowance/@BaggageAllowanceID (attribute) but Offer/OfferID (child) —
// and a key declared as a child element still falls back to an attribute of the
// same name, because implementations vary.
const ENTITY_KEYS = {
  Offer: "OfferID",
  OfferItem: "OfferItemID",
  FlightSegment: "SegmentID",
  PaxSegment: "PaxSegmentID",
  Fare: "FareCode",
  FareGroup: "@ListKey",
  FareItem: "FareItemID",
  FareComponent: "FareComponentID",
  Pax: "PaxID",
  OriginDest: "OriginDestID",
  Order: "OrderID",
  PaxJourney: "PaxJourneyID",
  PriceClass: "PriceClassID",
  BaggageAllowance: "BaggageAllowanceID",
  Service: "ServiceID",
  ServiceDefinition: "ServiceDefinitionID",
  Penalty: "PenaltyID",
  Disclosure: "@ListKey",
  Media: "MediaID",
  ContactInfo: "ContactInfoID",
};

// Minimum length of a shared *leading* fragment before it is treated as a
// regenerated batch identifier. Real payloads look like
//   XA67C09C8-37C4-4844-82B2-1  ->  XAA4633E4-E3C1-43D3-9153-1
// where the UUID-shaped prefix is reissued per response and the trailing number
// is what actually identifies the offer.
const CHURN_PREFIX_MIN_LEN = 12;

// A shared prefix containing a UUID is almost certainly a regenerated batch
// token, so a shorter overlap is still worth stripping there.
const UUID_RE = /[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/;
const CHURN_PREFIX_UUID_MIN_LEN = 6;

// Minimum length of a shared trailing fragment before it is treated as a
// per-response session token rather than meaningful data.
const CHURN_SUFFIX_MIN_LEN = 6;

// Fields regenerated on every response by definition (transport/session
// metadata, not business content). Reported separately so real changes stand out.
const VOLATILE_FIELDS = [
  "Timestamp",
  "TrxID",
  "CorrelationID",
  "EchoTokenText",
  "SequenceNumber",
  "TransactionID",
  "RequestID",
];

/** Strip a `{namespace}` prefix or `ns:` prefix from a tag name. */
function localname(tag) {
  if (!tag) return "";
  let name = tag;
  const brace = name.indexOf("}");
  if (name.startsWith("{") && brace !== -1) name = name.slice(brace + 1);
  const colon = name.indexOf(":");
  if (colon !== -1) name = name.slice(colon + 1);
  return name;
}

/**
 * Element children only, in document order.
 *
 * Browsers expose `.children`, but lighter DOM shims (e.g. the one used by the
 * Node verification harness) do not, so filter `childNodes` for element nodes
 * instead of relying on it.
 */
function elementChildren(element) {
  const out = [];
  for (const node of Array.from(element.childNodes || [])) {
    if (node.nodeType === 1) out.push(node);
  }
  return out;
}

/** Element children paired with their 1-based index among same-tag peers. */
function indexedChildren(element) {
  const counts = new Map();
  const out = [];
  for (const child of elementChildren(element)) {
    const tag = localname(child.tagName);
    const next = (counts.get(tag) || 0) + 1;
    counts.set(tag, next);
    out.push({ tag, index: next, element: child });
  }
  return out;
}

/**
 * The element's own direct text, excluding descendants' text.
 *
 * DOM `textContent` concatenates every descendant text node, whereas the Python
 * implementation uses lxml's `.text`, which is only the text before the first
 * child element. Using `textContent` here would attribute an entire subtree's
 * text to its parent and produce spurious value diffs, so collect direct text
 * nodes only.
 */
function directText(element) {
  let text = "";
  for (const node of Array.from(element.childNodes || [])) {
    // 3 === TEXT_NODE, 4 === CDATA_SECTION_NODE
    if (node.nodeType === 3 || node.nodeType === 4) {
      text += node.nodeValue || node.data || "";
    }
  }
  return text.trim();
}

/** Attributes as a sorted [name, value] list, namespace prefix stripped. */
function sortedAttrs(element) {
  const attrs = [];
  for (const attr of Array.from(element.attributes || [])) {
    attrs.push([localname(attr.name), (attr.value || "").trim()]);
  }
  attrs.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  return attrs;
}

/** Count signatures of a record list as a Map. */
function toCounter(records) {
  const counter = new Map();
  for (const record of records) {
    const key = `${record.struct}\u0000${record.value}`;
    counter.set(key, (counter.get(key) || 0) + 1);
  }
  return counter;
}

/** Multiset difference left - right, returning [key, count] pairs. */
function counterDiff(left, right) {
  const out = [];
  for (const [key, count] of left) {
    const other = right.get(key) || 0;
    if (count > other) out.push([key, count - other]);
  }
  return out;
}

/**
 * Flatten a document into comparable node records.
 * Element text and attributes each become their own record, so a changed price
 * surfaces as a changed value rather than a changed node.
 */
function flatten(root) {
  const records = [];

  const walk = (element, struct, path) => {
    for (const { tag, index, element: child } of indexedChildren(element)) {
      const childStruct = struct ? `${struct}/${tag}` : tag;
      const childPath = path ? `${path}/${tag}[${index}]` : `${tag}[${index}]`;

      for (const [name, value] of sortedAttrs(child)) {
        records.push({
          struct: `${childStruct}/@${name}`,
          path: `${childPath}/@${name}`,
          kind: "attribute",
          value,
        });
      }

      const text = (directText(child) || "").trim();
      const hasChildren = indexedChildren(child).length > 0;
      if (text && !hasChildren) {
        records.push({ struct: childStruct, path: childPath, kind: "text", value: text });
      }

      walk(child, childStruct, childPath);
    }
  };

  const tag = localname(root.tagName);
  const rootText = (directText(root) || "").trim();
  if (rootText && indexedChildren(root).length === 0) {
    records.push({ struct: tag, path: `${tag}[1]`, kind: "text", value: rootText });
  }
  for (const [name, value] of sortedAttrs(root)) {
    records.push({
      struct: `${tag}/@${name}`,
      path: `${tag}[1]/@${name}`,
      kind: "attribute",
      value,
    });
  }
  walk(root, tag, `${tag}[1]`);
  return records;
}

/**
 * Flatten one entity's own fields, not descending into nested entities.
 * Nested ID-bearing elements are compared under their own keys, so recreating
 * them here would report the same change twice.
 */
function flattenEntity(entityEl) {
  const tag = localname(entityEl.tagName);
  const records = [];

  const walk = (element, struct, path) => {
    for (const { tag: childTag, index, element: child } of indexedChildren(element)) {
      const childStruct = `${struct}/${childTag}`;
      const childPath = `${path}/${childTag}[${index}]`;

      if (ENTITY_KEYS[childTag] && childStruct !== `${tag}/${childTag}`) continue;

      for (const [name, value] of sortedAttrs(child)) {
        records.push({
          struct: `${childStruct}/@${name}`,
          path: `${childPath}/@${name}`,
          kind: "attribute",
          value,
        });
      }
      const text = (directText(child) || "").trim();
      if (text && indexedChildren(child).length === 0) {
        records.push({ struct: childStruct, path: childPath, kind: "text", value: text });
      }
      walk(child, childStruct, childPath);
    }
  };

  walk(entityEl, tag, `${tag}[1]`);
  return records;
}

/**
 * Identifying value per ID-bearing element, keyed by element tag.
 * Reads an attribute when the mapping says so ("@ListKey"), otherwise a child
 * element — and falls back to an attribute of the same name, because carriers
 * differ on which they use.
 */
function collectEntityIds(root) {
  const found = {};
  for (const element of descendants(root)) {
    const tag = localname(element.tagName);
    const spec = ENTITY_KEYS[tag];
    if (!spec) continue;
    const value = identifierValue(element, spec);
    if (!value) continue;
    if (!found[tag]) found[tag] = [];
    found[tag].push(value);
  }
  return found;
}

/** Read an element's identifying value per its ENTITY_KEYS specification. */
function identifierValue(element, spec) {
  let value = null;
  if (spec.charAt(0) === "@") {
    value = element.getAttribute(spec.slice(1));
  } else {
    for (const child of elementChildren(element)) {
      if (localname(child.tagName) === spec) {
        value = (directText(child) || "").trim() || null;
        break;
      }
    }
    if (!value) value = element.getAttribute(spec);
  }
  return value ? value.trim() : null;
}

/** Longest trailing fragment shared by every value. */
function commonSuffix(values) {
  if (!values.length) return "";
  let suffix = values[0];
  for (let i = 1; i < values.length; i += 1) {
    while (values[i].indexOf(suffix) !== values[i].length - suffix.length) {
      suffix = suffix.slice(1);
    }
    if (!suffix) return "";
  }
  return suffix;
}

/** Longest leading fragment shared by every value. */
function commonPrefix(values) {
  if (!values.length) return "";
  let prefix = values[0];
  for (let i = 1; i < values.length; i += 1) {
    while (values[i].indexOf(prefix) !== 0) {
      prefix = prefix.slice(0, -1);
    }
    if (!prefix) return "";
  }
  return prefix;
}

/**
 * Longest trailing fragment shared by every value, if it looks like a token.
 *
 * Some carriers regenerate the tail of each identifier per response, which would
 * otherwise make every entity look removed-and-added. The guard is a minimum
 * length: short shared tails are ordinary in real keys, so stripping them would
 * corrupt genuine data.
 */
function churnSuffix(values) {
  if (values.length < 2) return "";
  const limit = Math.min.apply(null, values.map((v) => v.length)) - 1;
  if (limit < CHURN_SUFFIX_MIN_LEN) return "";
  let suffix = commonSuffix(values);
  if (suffix.length > limit) suffix = suffix.slice(suffix.length - limit);
  return suffix.length >= CHURN_SUFFIX_MIN_LEN ? suffix : "";
}

/**
 * Longest leading fragment shared by every value, if it looks like a token.
 *
 * Offer identifiers are often built as "<regenerated-batch-uuid>-<ordinal>": a
 * fresh UUID per response with a stable ordinal. With the whole prefix reissued,
 * every offer appears removed and re-added, burying the real differences in
 * hundreds of noise lines. The guards are length-based, because plain numeric
 * identifiers such as SEG1/SEG2 share "SEG" and must not be touched.
 */
function churnPrefix(values) {
  if (values.length < 2) return "";
  const limit = Math.min.apply(null, values.map((v) => v.length)) - 1;
  let prefix = commonPrefix(values);
  if (!prefix) return "";
  if (prefix.length > limit) prefix = prefix.slice(0, limit);
  const uuid = UUID_RE.test(prefix);
  const threshold = uuid ? CHURN_PREFIX_UUID_MIN_LEN : CHURN_PREFIX_MIN_LEN;
  return prefix.length >= threshold ? prefix : "";
}

/**
 * Whether a name looks like an identifier.
 *
 * Carriers attach several identifier-like values to one element, and any can be
 * regenerated per response, so match on the name rather than a fixed list —
 * otherwise a new ID-bearing field silently reintroduces the churn noise.
 */
function isIdentifierName(name) {
  const lowered = String(name || "").toLowerCase();
  return (
    lowered.endsWith("id") ||
    lowered.endsWith("key") ||
    lowered.endsWith("ref") ||
    lowered.endsWith("reference") ||
    lowered.endsWith("token") ||
    lowered.endsWith("uuid") ||
    lowered.endsWith("guid")
  );
}

/**
 * Every identifier-like value, grouped by "tag\u0000field".
 * Covers attributes and child elements alike.
 */
function collectIdentifierValues(root) {
  const groups = {};
  for (const element of descendants(root)) {
    const tag = localname(element.tagName);
    const attrs = element.attributes || [];
    for (let i = 0; i < attrs.length; i += 1) {
      const name = localname(attrs[i].name);
      const value = (attrs[i].value || "").trim();
      if (value && isIdentifierName(name)) {
        const key = tag + "\u0000@" + name;
        if (!groups[key]) groups[key] = [];
        groups[key].push(value);
      }
    }
    for (const child of elementChildren(element)) {
      const childTag = localname(child.tagName);
      if (!isIdentifierName(childTag)) continue;
      const value = (directText(child) || "").trim();
      if (value) {
        const key = tag + "\u0000" + childTag;
        if (!groups[key]) groups[key] = [];
        groups[key].push(value);
      }
    }
  }
  return groups;
}

/** Churn-stripped mapping for each identifier group. */
function identifierNormalisation(values) {
  const result = {};
  Object.keys(values).forEach((key) => {
    const group = values[key];
    const prefix = churnPrefix(group);
    if (prefix) {
      const mapping = {};
      group.forEach((v) => (mapping[v] = v.slice(prefix.length)));
      result[key] = mapping;
      return;
    }
    const suffix = churnSuffix(group);
    const mapping = {};
    group.forEach((v) => {
      mapping[v] = suffix ? v.slice(0, v.length - suffix.length) : v;
    });
    result[key] = mapping;
  });
  return result;
}

/**
 * Rewrite churning identifier values in flattened records to stable forms.
 * Without this the structural pass sees every regenerated identifier as a
 * changed value.
 */
function applyIdentifierNormalisation(records, normalisation) {
  const keys = Object.keys(normalisation || {});
  if (!keys.length) return records;

  const bySuffix = {};
  keys.forEach((key) => {
    const parts = key.split("\u0000");
    bySuffix[parts[0] + "/" + parts[1]] = normalisation[key];
  });
  const suffixList = Object.keys(bySuffix);

  return records.map((record) => {
    for (const suffix of suffixList) {
      const mapping = bySuffix[suffix];
      if (
        record.struct.indexOf(suffix) === record.struct.length - suffix.length &&
        Object.prototype.hasOwnProperty.call(mapping, record.value)
      ) {
        const rewritten = mapping[record.value];
        if (rewritten === record.value) return record;
        return {
          struct: record.struct,
          path: record.path,
          kind: record.kind,
          value: rewritten,
        };
      }
    }
    return record;
  });
}

/** Collect ID-bearing entities keyed by "Tag\u0000normalised-id". */
function collectEntities(root) {
  const globalNormalisation = identifierNormalisation(collectIdentifierValues(root));

  const entities = new Map();
  for (const element of descendants(root)) {
    const tag = localname(element.tagName);
    const spec = ENTITY_KEYS[tag];
    if (!spec) continue;

    const raw = identifierValue(element, spec);
    if (!raw) continue;

    // Reuse the same churn handling as the structural pass so entity keys and
    // record values stay consistent even when the field is not the declared
    // identity (Offer/@OfferID versus Fare/@ListKey, say).
    const idName = spec.charAt(0) === "@" ? spec.slice(1) : spec;
    const mapping =
      globalNormalisation[tag + "\u0000@" + idName] ||
      globalNormalisation[tag + "\u0000" + idName];
    const key = mapping && mapping[raw] ? mapping[raw] : raw;

    // Keep every record describing the entity except its own identifier, so two
    // instances with the same id compare field-by-field. Nested identifiers are
    // normalised too, otherwise a reissued child id inside an otherwise
    // unchanged parent reports as a content change.
    const idStructs = [tag + "/" + idName, tag + "/@" + idName];
    let scoped = flattenEntity(element).filter(
      (r) => !(r.value === raw && idStructs.indexOf(r.struct) !== -1)
    );
    scoped = applyIdentifierNormalisation(scoped, globalNormalisation);

    const composite = tag + "\u0000" + key;
    if (!entities.has(composite)) entities.set(composite, []);
    entities.get(composite).push(...scoped);
  }
  return entities;
}

/** Depth-first list of every descendant element (excluding the root itself). */
function descendants(root) {
  const out = [];
  const walk = (element) => {
    for (const child of elementChildren(element)) {
      out.push(child);
      walk(child);
    }
  };
  walk(root);
  return out;
}

/** Parse an XML string, throwing a readable error on malformed input. */
function parseXml(text) {
  const doc = new DOMParser().parseFromString(text, "application/xml");
  // Browsers report parse failures with a <parsererror> element; DOM shims vary
  // in how (or whether) they expose it, so walk the tree rather than relying on
  // querySelector, which not every implementation provides.
  const all = [];
  const walk = (element) => {
    for (const child of elementChildren(element)) {
      all.push(child);
      walk(child);
    }
  };
  walk(doc.documentElement);
  const error = all.find((el) => localname(el.tagName) === "parsererror");
  if (error) {
    const detail = (error.textContent || "malformed XML").split("\n")[0].trim();
    throw new Error(`invalid XML: ${detail}`);
  }
  if (!doc.documentElement) throw new Error("invalid XML: no document element");
  return doc.documentElement;
}

/** Inventory of an NDC message: root, version, node count and entity IDs. */
function summarizeMessage(root, label = "message") {
  const entities = {};
  const all = descendants(root);
  for (const element of all) {
    const tag = localname(element.tagName);
    const idChild = ENTITY_KEYS[tag];
    if (!idChild) continue;
    for (const child of elementChildren(element)) {
      if (localname(child.tagName) === idChild) {
        const value = (directText(child) || "").trim();
        if (value) {
          if (!entities[tag]) entities[tag] = [];
          entities[tag].push(value);
        }
        break;
      }
    }
  }
  const counts = {};
  for (const [k, v] of Object.entries(entities)) counts[k] = v.length;
  return {
    label,
    root: localname(root.tagName),
    version: root.getAttribute("Version"),
    node_count: all.length + 1,
    entity_ids: entities,
    entity_counts: counts,
  };
}

/**
 * Compute the structural and entity-level diff between two NDC messages.
 * Mirrors diff_xml() in src/airshop/ndc/diff.py.
 */
function diffXml(baseXml, newXml, baseLabel = "baseline", newLabel = "new") {
  const baseRoot = parseXml(baseXml);
  const newRoot = parseXml(newXml);

  const report = {
    base: baseLabel,
    new: newLabel,
    identical: false,
    missing_nodes: {},
    extra_nodes: {},
    value_diffs: [],
    entities_removed: [],
    entities_added: [],
    entities_modified: [],
  };

  // --- structural pass ---------------------------------------------------- //
  // Identifiers whose prefix or suffix is regenerated per response are rewritten
  // to their stable form before any comparison, otherwise every reissued id
  // would masquerade as a value change.
  const baseRecords = applyIdentifierNormalisation(
    flatten(baseRoot),
    identifierNormalisation(collectIdentifierValues(baseRoot))
  );
  const newRecords = applyIdentifierNormalisation(
    flatten(newRoot),
    identifierNormalisation(collectIdentifierValues(newRoot))
  );

  const baseStruct = new Map();
  const newStruct = new Map();
  for (const r of baseRecords) baseStruct.set(r.struct, (baseStruct.get(r.struct) || 0) + 1);
  for (const r of newRecords) newStruct.set(r.struct, (newStruct.get(r.struct) || 0) + 1);

  for (const [path, count] of baseStruct) {
    const other = newStruct.get(path) || 0;
    if (count > other) report.missing_nodes[path] = count - other;
  }
  for (const [path, count] of newStruct) {
    const other = baseStruct.get(path) || 0;
    if (count > other) report.extra_nodes[path] = count - other;
  }

  // Value-level differences at a path that exists in both documents.
  const structures = Array.from(new Set([...baseStruct.keys(), ...newStruct.keys()])).sort();
  for (const struct of structures) {
    if (!baseStruct.has(struct) || !newStruct.has(struct)) continue;

    const baseVals = new Map();
    const newVals = new Map();
    for (const r of baseRecords) {
      if (r.struct === struct) baseVals.set(r.value, (baseVals.get(r.value) || 0) + 1);
    }
    for (const r of newRecords) {
      if (r.struct === struct) newVals.set(r.value, (newVals.get(r.value) || 0) + 1);
    }

    const missingValues = expand(counterDiff(baseVals, newVals));
    const extraValues = expand(counterDiff(newVals, baseVals));
    if (missingValues.length || extraValues.length) {
      const sample = baseRecords.find((r) => r.struct === struct);
      report.value_diffs.push({
        path: sample ? sample.path : struct,
        struct,
        missing_values: missingValues,
        extra_values: extraValues,
      });
    }
  }

  // --- entity pass -------------------------------------------------------- //
  const baseEntities = collectEntities(baseRoot);
  const newEntities = collectEntities(newRoot);
  const churnedTags = new Set();

  const allKeys = Array.from(
    new Set([...baseEntities.keys(), ...newEntities.keys()])
  ).sort();

  for (const composite of allKeys) {
    const [entity, key] = composite.split("\u0000");
    const inBase = baseEntities.has(composite);
    const inNew = newEntities.has(composite);

    if (inBase && !inNew) {
      report.entities_removed.push({ entity, key, change: "removed", missing: [], extra: [] });
      churnedTags.add(entity);
    } else if (inNew && !inBase) {
      report.entities_added.push({ entity, key, change: "added", missing: [], extra: [] });
      churnedTags.add(entity);
    } else {
      const baseMap = toCounter(baseEntities.get(composite));
      const newMap = toCounter(newEntities.get(composite));
      const missing = expand(counterDiff(baseMap, newMap)).map((s) => renderSig(s));
      const extra = expand(counterDiff(newMap, baseMap)).map((s) => renderSig(s));
      if (missing.length || extra.length) {
        report.entities_modified.push({
          entity,
          key,
          change: "modified",
          missing: missing.sort(),
          extra: extra.sort(),
        });
      }
    }
  }

  // Value diffs nested inside a churned entity tag are already reported per
  // entity; suppressing them keeps the report free of duplicate noise.
  if (churnedTags.size) {
    report.value_diffs = report.value_diffs.filter((v) => {
      const hay = `${v.struct}/`;
      let churned = false;
      churnedTags.forEach((tag) => {
        if (hay.includes(`/${tag}/`)) churned = true;
      });
      return !churned;
    });
  }

  // Session/transport metadata is regenerated on every response by definition,
  // so it is separated out rather than reported as content churn.
  report.session_metadata = [];
  report.value_diffs = report.value_diffs.filter((v) => {
    const last = v.struct.split("/").pop().replace(/^@/, "");
    if (VOLATILE_FIELDS.indexOf(last) !== -1) {
      report.session_metadata.push(v);
      return false;
    }
    return true;
  });

  report.identical =
    Object.keys(report.missing_nodes).length === 0 &&
    Object.keys(report.extra_nodes).length === 0 &&
    report.value_diffs.length === 0 &&
    report.entities_removed.length === 0 &&
    report.entities_added.length === 0 &&
    report.entities_modified.length === 0;

  return report;
}

/** Expand [key, count] pairs into repeated key entries. */
function expand(pairs) {
  const out = [];
  for (const [key, count] of pairs) for (let i = 0; i < count; i += 1) out.push(key);
  return out;
}

/** Turn a "struct\u0000value" counter key into "struct = 'value'". */
function renderSig(key) {
  const idx = key.indexOf("\u0000");
  const struct = key.slice(0, idx);
  const value = key.slice(idx + 1);
  return `${struct} = '${value}'`;
}

return {
  ENTITY_KEYS: ENTITY_KEYS,
  VOLATILE_FIELDS: VOLATILE_FIELDS,
  localname: localname,
  parseXml: parseXml,
  flatten: flatten,
  collectEntities: collectEntities,
  collectEntityIds: collectEntityIds,
  collectIdentifierValues: collectIdentifierValues,
  identifierNormalisation: identifierNormalisation,
  applyIdentifierNormalisation: applyIdentifierNormalisation,
  descendants: descendants,
  churnSuffix: churnSuffix,
  churnPrefix: churnPrefix,
  summarizeMessage: summarizeMessage,
  diffXml: diffXml,
};
});
