/*
 * NDC AirShopping diff engine — port of src/airshop/ndc/diff.py.
 *
 * Runs entirely in the browser: no server, no Python, no network. The algorithms
 * are ported one-for-one from the Python implementation so both produce the same
 * report for the same inputs; web/verify.mjs asserts that equivalence against a
 * reference report generated by the Python code.
 *
 * Packaged as a UMD-style global/CommonJS module rather than an ES module, so
 * index.html also works when opened directly from disk (file://), where browsers
 * block ES module loading.
 */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (typeof globalThis !== "undefined") globalThis.NDC = api;
  if (root && typeof root === "object") root.NDC = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

// ID-bearing NDC collections: element name -> child element holding its key.
const ENTITY_KEYS = {
  Offer: "OfferID",
  OfferItem: "OfferItemID",
  FlightSegment: "SegmentID",
  Fare: "FareCode",
  Pax: "PaxID",
  OriginDest: "OriginDestID",
  Order: "OrderID",
  PaxJourney: "PaxJourneyID",
  PriceClass: "PriceClassID",
  BaggageAllowance: "BaggageAllowanceID",
};

/** Strip a `{namespace}` prefix or `ns:` prefix from a tag name. */
function localname(tag) {
  if (!tag) return "";
  let name = tag;
  const brace = name.indexOf("}");
  if (name.startsWith("{") && brace !== -1) name = name.slice(brace + 1);
  const colon = name.indexOf(":");
  if (colon !== -1) name = name.slice(colon + 1);
  return name;
}

/**
 * Element children only, in document order.
 *
 * Browsers expose `.children`, but lighter DOM shims (e.g. the one used by the
 * Node verification harness) do not, so filter `childNodes` for element nodes
 * instead of relying on it.
 */
function elementChildren(element) {
  const out = [];
  for (const node of Array.from(element.childNodes || [])) {
    if (node.nodeType === 1) out.push(node);
  }
  return out;
}

/** Element children paired with their 1-based index among same-tag peers. */
function indexedChildren(element) {
  const counts = new Map();
  const out = [];
  for (const child of elementChildren(element)) {
    const tag = localname(child.tagName);
    const next = (counts.get(tag) || 0) + 1;
    counts.set(tag, next);
    out.push({ tag, index: next, element: child });
  }
  return out;
}

/**
 * The element's own direct text, excluding descendants' text.
 *
 * DOM `textContent` concatenates every descendant text node, whereas the Python
 * implementation uses lxml's `.text`, which is only the text before the first
 * child element. Using `textContent` here would attribute an entire subtree's
 * text to its parent and produce spurious value diffs, so collect direct text
 * nodes only.
 */
function directText(element) {
  let text = "";
  for (const node of Array.from(element.childNodes || [])) {
    // 3 === TEXT_NODE, 4 === CDATA_SECTION_NODE
    if (node.nodeType === 3 || node.nodeType === 4) {
      text += node.nodeValue || node.data || "";
    }
  }
  return text.trim();
}

/** Attributes as a sorted [name, value] list, namespace prefix stripped. */
function sortedAttrs(element) {
  const attrs = [];
  for (const attr of Array.from(element.attributes || [])) {
    attrs.push([localname(attr.name), (attr.value || "").trim()]);
  }
  attrs.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  return attrs;
}

/** Count signatures of a record list as a Map. */
function toCounter(records) {
  const counter = new Map();
  for (const record of records) {
    const key = `${record.struct}\u0000${record.value}`;
    counter.set(key, (counter.get(key) || 0) + 1);
  }
  return counter;
}

/** Multiset difference left - right, returning [key, count] pairs. */
function counterDiff(left, right) {
  const out = [];
  for (const [key, count] of left) {
    const other = right.get(key) || 0;
    if (count > other) out.push([key, count - other]);
  }
  return out;
}

/**
 * Flatten a document into comparable node records.
 * Element text and attributes each become their own record, so a changed price
 * surfaces as a changed value rather than a changed node.
 */
function flatten(root) {
  const records = [];

  const walk = (element, struct, path) => {
    for (const { tag, index, element: child } of indexedChildren(element)) {
      const childStruct = struct ? `${struct}/${tag}` : tag;
      const childPath = path ? `${path}/${tag}[${index}]` : `${tag}[${index}]`;

      for (const [name, value] of sortedAttrs(child)) {
        records.push({
          struct: `${childStruct}/@${name}`,
          path: `${childPath}/@${name}`,
          kind: "attribute",
          value,
        });
      }

      const text = (directText(child) || "").trim();
      const hasChildren = indexedChildren(child).length > 0;
      if (text && !hasChildren) {
        records.push({ struct: childStruct, path: childPath, kind: "text", value: text });
      }

      walk(child, childStruct, childPath);
    }
  };

  const tag = localname(root.tagName);
  const rootText = (directText(root) || "").trim();
  if (rootText && indexedChildren(root).length === 0) {
    records.push({ struct: tag, path: `${tag}[1]`, kind: "text", value: rootText });
  }
  for (const [name, value] of sortedAttrs(root)) {
    records.push({
      struct: `${tag}/@${name}`,
      path: `${tag}[1]/@${name}`,
      kind: "attribute",
      value,
    });
  }
  walk(root, tag, `${tag}[1]`);
  return records;
}

/**
 * Flatten one entity's own fields, not descending into nested entities.
 * Nested ID-bearing elements are compared under their own keys, so recreating
 * them here would report the same change twice.
 */
function flattenEntity(entityEl) {
  const tag = localname(entityEl.tagName);
  const records = [];

  const walk = (element, struct, path) => {
    for (const { tag: childTag, index, element: child } of indexedChildren(element)) {
      const childStruct = `${struct}/${childTag}`;
      const childPath = `${path}/${childTag}[${index}]`;

      if (ENTITY_KEYS[childTag] && childStruct !== `${tag}/${childTag}`) continue;

      for (const [name, value] of sortedAttrs(child)) {
        records.push({
          struct: `${childStruct}/@${name}`,
          path: `${childPath}/@${name}`,
          kind: "attribute",
          value,
        });
      }
      const text = (directText(child) || "").trim();
      if (text && indexedChildren(child).length === 0) {
        records.push({ struct: childStruct, path: childPath, kind: "text", value: text });
      }
      walk(child, childStruct, childPath);
    }
  };

  walk(entityEl, tag, `${tag}[1]`);
  return records;
}

/** Collect ID-bearing entities keyed by "Tag\u0000id". */
function collectEntities(root) {
  const entities = new Map();
  for (const element of descendants(root)) {
    const tag = localname(element.tagName);
    const idChild = ENTITY_KEYS[tag];
    if (!idChild) continue;

    let key = null;
    for (const child of elementChildren(element)) {
      if (localname(child.tagName) === idChild) {
        key = (directText(child) || "").trim() || null;
        break;
      }
    }
    if (!key) continue;

    // Keep every record describing the entity except the ID itself.
    const idStruct = `${tag}/${idChild}`;
    const scoped = flattenEntity(element).filter(
      (r) => !(r.struct === idStruct && r.value === key)
    );
    const composite = `${tag}\u0000${key}`;
    if (!entities.has(composite)) entities.set(composite, []);
    entities.get(composite).push(...scoped);
  }
  return entities;
}

/** Depth-first list of every descendant element (excluding the root itself). */
function descendants(root) {
  const out = [];
  const walk = (element) => {
    for (const child of elementChildren(element)) {
      out.push(child);
      walk(child);
    }
  };
  walk(root);
  return out;
}

/** Parse an XML string, throwing a readable error on malformed input. */
function parseXml(text) {
  const doc = new DOMParser().parseFromString(text, "application/xml");
  // Browsers report parse failures with a <parsererror> element; DOM shims vary
  // in how (or whether) they expose it, so walk the tree rather than relying on
  // querySelector, which not every implementation provides.
  const all = [];
  const walk = (element) => {
    for (const child of elementChildren(element)) {
      all.push(child);
      walk(child);
    }
  };
  walk(doc.documentElement);
  const error = all.find((el) => localname(el.tagName) === "parsererror");
  if (error) {
    const detail = (error.textContent || "malformed XML").split("\n")[0].trim();
    throw new Error(`invalid XML: ${detail}`);
  }
  if (!doc.documentElement) throw new Error("invalid XML: no document element");
  return doc.documentElement;
}

/** Inventory of an NDC message: root, version, node count and entity IDs. */
function summarizeMessage(root, label = "message") {
  const entities = {};
  const all = descendants(root);
  for (const element of all) {
    const tag = localname(element.tagName);
    const idChild = ENTITY_KEYS[tag];
    if (!idChild) continue;
    for (const child of elementChildren(element)) {
      if (localname(child.tagName) === idChild) {
        const value = (directText(child) || "").trim();
        if (value) {
          if (!entities[tag]) entities[tag] = [];
          entities[tag].push(value);
        }
        break;
      }
    }
  }
  const counts = {};
  for (const [k, v] of Object.entries(entities)) counts[k] = v.length;
  return {
    label,
    root: localname(root.tagName),
    version: root.getAttribute("Version"),
    node_count: all.length + 1,
    entity_ids: entities,
    entity_counts: counts,
  };
}

/**
 * Compute the structural and entity-level diff between two NDC messages.
 * Mirrors diff_xml() in src/airshop/ndc/diff.py.
 */
function diffXml(baseXml, newXml, baseLabel = "baseline", newLabel = "new") {
  const baseRoot = parseXml(baseXml);
  const newRoot = parseXml(newXml);

  const report = {
    base: baseLabel,
    new: newLabel,
    identical: false,
    missing_nodes: {},
    extra_nodes: {},
    value_diffs: [],
    entities_removed: [],
    entities_added: [],
    entities_modified: [],
  };

  // --- structural pass ---------------------------------------------------- //
  const baseRecords = flatten(baseRoot);
  const newRecords = flatten(newRoot);

  const baseStruct = new Map();
  const newStruct = new Map();
  for (const r of baseRecords) baseStruct.set(r.struct, (baseStruct.get(r.struct) || 0) + 1);
  for (const r of newRecords) newStruct.set(r.struct, (newStruct.get(r.struct) || 0) + 1);

  for (const [path, count] of baseStruct) {
    const other = newStruct.get(path) || 0;
    if (count > other) report.missing_nodes[path] = count - other;
  }
  for (const [path, count] of newStruct) {
    const other = baseStruct.get(path) || 0;
    if (count > other) report.extra_nodes[path] = count - other;
  }

  // Value-level differences at a path that exists in both documents.
  const structures = Array.from(new Set([...baseStruct.keys(), ...newStruct.keys()])).sort();
  for (const struct of structures) {
    if (!baseStruct.has(struct) || !newStruct.has(struct)) continue;

    const baseVals = new Map();
    const newVals = new Map();
    for (const r of baseRecords) {
      if (r.struct === struct) baseVals.set(r.value, (baseVals.get(r.value) || 0) + 1);
    }
    for (const r of newRecords) {
      if (r.struct === struct) newVals.set(r.value, (newVals.get(r.value) || 0) + 1);
    }

    const missingValues = expand(counterDiff(baseVals, newVals));
    const extraValues = expand(counterDiff(newVals, baseVals));
    if (missingValues.length || extraValues.length) {
      const sample = baseRecords.find((r) => r.struct === struct);
      report.value_diffs.push({
        path: sample ? sample.path : struct,
        struct,
        missing_values: missingValues,
        extra_values: extraValues,
      });
    }
  }

  // --- entity pass -------------------------------------------------------- //
  const baseEntities = collectEntities(baseRoot);
  const newEntities = collectEntities(newRoot);
  const churnedTags = new Set();

  const allKeys = Array.from(
    new Set([...baseEntities.keys(), ...newEntities.keys()])
  ).sort();

  for (const composite of allKeys) {
    const [entity, key] = composite.split("\u0000");
    const inBase = baseEntities.has(composite);
    const inNew = newEntities.has(composite);

    if (inBase && !inNew) {
      report.entities_removed.push({ entity, key, change: "removed", missing: [], extra: [] });
      churnedTags.add(entity);
    } else if (inNew && !inBase) {
      report.entities_added.push({ entity, key, change: "added", missing: [], extra: [] });
      churnedTags.add(entity);
    } else {
      const baseMap = toCounter(baseEntities.get(composite));
      const newMap = toCounter(newEntities.get(composite));
      const missing = expand(counterDiff(baseMap, newMap)).map((s) => renderSig(s));
      const extra = expand(counterDiff(newMap, baseMap)).map((s) => renderSig(s));
      if (missing.length || extra.length) {
        report.entities_modified.push({
          entity,
          key,
          change: "modified",
          missing: missing.sort(),
          extra: extra.sort(),
        });
      }
    }
  }

  // Value diffs nested inside a churned entity tag are already reported per
  // entity; suppressing them keeps the report free of duplicate noise.
  if (churnedTags.size) {
    report.value_diffs = report.value_diffs.filter((v) => {
      const hay = `${v.struct}/`;
      for (const tag of churnedTags) if (hay.includes(`/${tag}/`)) return false;
      return true;
    });
  }

  report.identical =
    Object.keys(report.missing_nodes).length === 0 &&
    Object.keys(report.extra_nodes).length === 0 &&
    report.value_diffs.length === 0 &&
    report.entities_removed.length === 0 &&
    report.entities_added.length === 0 &&
    report.entities_modified.length === 0;

  return report;
}

/** Expand [key, count] pairs into repeated key entries. */
function expand(pairs) {
  const out = [];
  for (const [key, count] of pairs) for (let i = 0; i < count; i += 1) out.push(key);
  return out;
}

/** Turn a "struct\u0000value" counter key into "struct = 'value'". */
function renderSig(key) {
  const idx = key.indexOf("\u0000");
  const struct = key.slice(0, idx);
  const value = key.slice(idx + 1);
  return `${struct} = '${value}'`;
}

return {
  ENTITY_KEYS: ENTITY_KEYS,
  localname: localname,
  parseXml: parseXml,
  flatten: flatten,
  collectEntities: collectEntities,
  descendants: descendants,
  summarizeMessage: summarizeMessage,
  diffXml: diffXml,
};
});
